name: ✨ Feature Request
description: Suggest an improvement or new feature for the curriculum
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## Suggest a Feature
        Have an idea to improve the QA Fundamentals program? Let us know!

  - type: dropdown
    id: category
    attributes:
      label: Category
      description: What area does this feature relate to?
      options:
        - Curriculum Content
        - Exercises
        - Tutorials
        - Templates
        - Documentation
        - Tooling/Automation
        - Other
    validations:
      required: true

  - type: dropdown
    id: week
    attributes:
      label: Related Week (if applicable)
      options:
        - Week 1 - QA Foundations
        - Week 2 - Test Levels
        - Week 3 - Functional Testing
        - Week 4 - Non-Functional Testing
        - Week 5 - Test Design (Basic)
        - Week 6 - Test Design (Advanced)
        - Week 7 - Test Planning
        - Week 8 - Test Case Management
        - Week 9 - Agile Testing
        - Week 10 - Defect Management
        - Week 11 - Python Basics
        - General/Multiple Weeks
    validations:
      required: false

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Currently, learners struggle with...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you solve this problem?
      placeholder: Add a new exercise that...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other solutions did you consider?

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - High (blocking learning)
        - Medium (would significantly improve experience)
        - Low (nice to have)
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other information, mockups, or examples

  - type: checkboxes
    id: checks
    attributes:
      label: Checklist
      options:
        - label: I searched existing issues and this is not a duplicate
          required: true
        - label: This feature aligns with the program's learning objectives
          required: true
